### ISSUE TITLE
Refactor Clickable Component

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#782]
# Description
This issue is related to refactoring the `Clickable` Component.

## Acceptance Criteria
Refactor the component from a [class component to a function component](https://reactjs.org/docs/components-and-props.html#function-and-class-components).
Feel free to contribute other improvements to the component while refactoring if you notice any. 

Refer to other components to keep formatting consistent. For example, reference the [Badge](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badge.tsx), [BadgeButton](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badgeButton.tsx), or [Tabs](https://github.com/dcos-labs/ui-kit/blob/main/packages/tabs/components/Tabs.tsx) components.

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch. Please adhere to branch formatting, for example `<your_initials>/refactor/<component_name>`
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing be sure to prefix with the appropriate conventional commit type. For example, `refactor: button component`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready to review" label when complete.

**Comment by nataliepina** [comment]
Hi @vishnusnathann any progress on this issue? Please let us know if you need any help. Thanks!

**Comment by vishnusnathann** [comment]
@nataliepina I was able to update the component to FC but the tests were getting failed.

**Comment by nataliepina** [comment]
> @nataliepina I was able to update the component to FC but the tests were getting failed.

Had you updated the snapshots with `npm run test -- -u`, try that out if not. Otherwise, if you can push up the code and create a pull request we'd be happy to take a look and offer some suggestions to fix the tests.

**Comment by vishnusnathann** [comment]
Hi @nataliepina Created the PR https://github.com/dcos-labs/ui-kit/pull/808
