### ISSUE TITLE
Refactor DialogModal Component

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#784]
# Description
This issue is related to refactoring the `DialogModal` Component.

## Acceptance Criteria
Refactor the component from a [class component to a function component](https://reactjs.org/docs/components-and-props.html#function-and-class-components).
Feel free to contribute other improvements to the component while refactoring if you notice any.
Components may require updates to wrapping or related components. 

Refer to other components to keep formatting consistent. For example, reference the [Badge](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badge.tsx), [BadgeButton](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badgeButton.tsx), or [Tabs](https://github.com/dcos-labs/ui-kit/blob/main/packages/tabs/components/Tabs.tsx) components.

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing be sure to prefix with the appropriate conventional commit type. For example, `refactor: button component`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready to review" label when complete.

**Comment by ShivanshCharak** [comment]
hi @nataliepina  i would like to contribute to this issue

**Comment by nataliepina** [comment]
@ShivanshCharak assigning it over to you, thanks.

**Comment by nataliepina** [comment]
Hey, @ShivanshCharak have you been able to make any progress here? Please let us know if you need any help.

**Comment by nataliepina** [comment]
We haven't heard from you in a bit @ShivanshCharak so I'm going to go ahead and unassign this issue so that someone else can grab it.

**Comment by nataliepina** [comment]
@davidtaing this one has opened back up if you have any interest, but no pressure.

**Comment by davidtaing** [comment]
Thanks @nataliepina, I'll take this.

**Comment by nataliepina** [comment]
Thanks, @davidtaing 🙌🏻  If it ends up requiring updates to other modal-related components h and that becomes a lot feel free to reach out.
