### ISSUE TITLE
Refactor button from a class component to a function component

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#792]
# Description
This issue is related to refactoring the `ButtonBase` Component.

## Acceptance Criteria
Refactor the `ButtonBase` component from a [class component to a function component](https://reactjs.org/docs/components-and-props.html#function-and-class-components).
Feel free to contribute other improvements to the component while refactoring if you notice any. 

Refer to other components to keep formatting consistent. For example, reference the [Badge](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badge.tsx), [BadgeButton](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badgeButton.tsx), or [Tabs](https://github.com/dcos-labs/ui-kit/blob/main/packages/tabs/components/Tabs.tsx) components.

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing be sure to prefix with the appropriate conventional commit type. For example, `refactor: buttonbase component`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready to review" label when complete.

**Comment by Adw8** [comment]
Hi @nataliepina, I would like to work on this issue, Can you assign it to me?

**Comment by nataliepina** [comment]
Hi @Adw8 have you been able to start refactoring? Please let us know if you need any help with anything. Cheers!

**Comment by Adw8** [comment]
Hello @nataliepina, I have been able to start, I'll keep you updated and let you know if I need any help, Thanks!

**Comment by nataliepina** [comment]
Hi @Adw8, are you able to get this into a pull request this week? We're happy to provide feedback there to get this across the finish line. Otherwise, we may start the refactoring of this next week.

**Comment by Adw8** [comment]
Hi @nataliepina, Unfortunately, I will not be able to complete this issue, Kindly assign it to someone else, Apologies for the inconvenience!

**Comment by nataliepina** [comment]
No problem, thank you for the update.
