### ISSUE TITLE
Refactor TextInput related components from classes to functional components

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#800]
# Description
This issue is related to refactoring the `TextInput` related components. 
Refactoring will require changes to the `TextInput`, `TextInputWithIcon`, `TextInputWithButtons` and `TextInputWithBadges` as well. Failures will happen if all of these are not refactored so this task will be a bit more involved than the other open issues. 

Kudos for taking on this task! 

## Acceptance Criteria
Refactor the component from a [class component to a function component](https://reactjs.org/docs/components-and-props.html#function-and-class-components).
Feel free to contribute other improvements to the component while refactoring if you notice any. 

Refer to other components to keep formatting consistent. For example, reference the [Badge](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badge.tsx), [BadgeButton](https://github.com/dcos-labs/ui-kit/blob/main/packages/badge/components/badgeButton.tsx), or [Tabs](https://github.com/dcos-labs/ui-kit/blob/main/packages/tabs/components/Tabs.tsx) components.

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing be sure to prefix with the appropriate conventional commit type. For example, `refactor: button component`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready to review" label when complete.

**Comment by alberturria** [comment]
Hey @nataliepina could I work on this issue? 🙂

**Comment by nataliepina** [comment]
Absolutely, thanks @alberturria, assigning it over to you!

**Comment by alberturria** [comment]
@nataliepina I've seen that you were using inheritance for building some of these components. As a side effect of refactor them to functional components, and don't duplicate the code, I need to extract some methods to a common place.
I was thinking on create a new file called `common.ts` or `utils.ts` at `textInput/components`.
What do you think? Happy to hear your thoughts🙂

**Comment by nataliepina** [comment]
@alberturria That would be a great improvement. Any improvements you can think of are very much welcome. Thank you for contributing!
