### ISSUE TITLE
Migrate Typeahead component test from Enzyme to React Testing Library 

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#803]
# Description
This issue is related to refactoring the `Typeahead` related tests.

We've recently been migrating our tests from Jest + Enzyme to Jest + testing-library/react to support a full migration to React 18.

You may refer to this previous PR beginning the migration for code examples - https://github.com/dcos-labs/ui-kit/pull/771. 

## Acceptance Criteria
Refactor the test to use [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) instead of [Enzyme](https://www.npmjs.com/package/enzyme) (which is no longer supported with React 18). 

More information: [Migrate from Enzyme](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/)

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch. Please adhere to branch formatting, for example `<your_initials>/refactor/<component_name>-test`
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing be sure to prefix with the appropriate conventional commit type. For example, `refactor: <component_name> test`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready to review" label when complete.

**Comment by leonardomaier** [comment]
Hi @nataliepina, I'm currently working on this, could you please assign me to it?
