### ISSUE TITLE
Migrate Modal component tests from Enzyme to React Testing Library

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#819]
# Description
This issue is related to refactoring the `Modal.test.tsx` file. 

We've recently been migrating our tests from Jest + Enzyme to Jest + testing-library/react to support a full migration to React 18.

You may refer to this previous PR beginning the migration for code examples - https://github.com/dcos-labs/ui-kit/pull/771. 

## Acceptance Criteria
Refactor the test to use [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) instead of [Enzyme](https://www.npmjs.com/package/enzyme) (which is no longer supported with React 18). 

More information: [Migrate from Enzyme](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/)

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `refactor: <component_name> tests`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready for review" label when complete.

**Comment by deek121477** [comment]
Can I work on this issue?

**Comment by nataliepina** [comment]
Absolutely, thanks @deek121477.

**Comment by deek121477** [comment]
> Absolutely, thanks @deek121477.

Thanks!!

**Comment by nataliepina** [comment]
Hi @deek121477 are you able to create a pull request for these changes soon? Hacktoberfest will be coming to a close soon. Please let us know if you need any help.

**Comment by deek121477** [comment]
> Hi @deek121477 are you able to create a pull request for these changes? Hacktoberfest will be coming to a close soon. Please let us know if you need any help.

Yes. I'm working on it. I will need few days.

**Comment by nataliepina** [comment]
> Yes. I'm working on it. I will need few days.
No problem, thanks for the update. I wanted to make sure you get the Hacktoberfest credit. 😄

**Comment by nataliepina** [comment]
Apologies @deek121477 but we've now done this work as it became a blocker. We need to finish our refactors to react testing library for work to update to React 18 happening in our current sprint. There will be other opportunities to contribute in the future, we welcome your contributions. Cheers!
