### ISSUE TITLE
Update to Webpack 5

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#855]
# Description
We'd like to update from Webpack 4 to Webpack 5. 

The new version of Storybook (7) is in alpha testing and set to release soon. With this new version, Webpack 5 will be suggested. Upgrading Webpack will allow for build optimizations, such as lazy compilation and filesystem caching. 

There may be some caveats to this update alongside Storybook and some research to be done there to resolve any issue while updating. 

More info: https://storybook.js.org/docs/react/builders/webpack#webpack-5

## Acceptance Criteria

Update to Webpack 5

Clean up our existing Webpack setup. Can it be consolidated into 1 file instead of 2?

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `refactor: <component_name> tests`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready for review" label when complete.

**Comment by nataliepina** [comment]
Thanks @taksuparth let us know if you have any trouble.

**Comment by taksuparth** [comment]
@nataliepina I will be picking this up in the upcoming weekend.

**Comment by nataliepina** [comment]
Hey @taksuparth 😃  Are you in progress on this one yet?

**Comment by taksuparth** [comment]
Hi @nataliepina! I could not find time to pick this up yet. Give me 1 week's time, I will inform here if I won't be able to pick this up.

**Comment by nataliepina** [comment]
No problem at all @taksuparth, thanks!

**Comment by nataliepina** [comment]
Checking back in @taksuparth are you able to complete this one? It's blocking some other upgrades and will be a very important feature to improve ui-kit. Your contribution would be highly appreciated! Thanks.

**Comment by taksuparth** [comment]
@nataliepina I have started working on it but couldn't find a time stretch to finish every aspect of the task. Plus, I am traveling for the next 2 weeks, so I won't be able to pick it up. You can unassign me from this task as of now. Once I will be back and if it is not picked, I will finish it.

**Comment by mstruebing** [comment]
@taksuparth If you want and find the time you could create a work-in-progress PR so that we could use the work you've already done. No pressure if you are not able to do that! 
I've unassigned you from that task.

**Comment by taksuparth** [comment]
Sure, I will share WIP PR in sometime

**Comment by nataliepina** [comment]
We can definitely work with your changes if you still have the availability to get that into a pull request sometime soon @taksuparth. Thanks!
