### ISSUE TITLE
Bug Fix - Sortable Table header chevron should be clickable

### ISSUE THREAD

**Issue by nataliepina** [dcos-labs/ui-kit#856]
# Description
The chevron next to the table header column should be clickable. Currently, the table headers will only sort when the header text is clicked on but the user should also be able to click on the chevron/arrow, it is created with `::after` which is part of the issue. 

See this story to explore the buggy behavior - https://dcos-labs.github.io/ui-kit/?path=/story/data-listing-table--sortable-columns

Here is a video example of this behavior - https://www.loom.com/share/aeaca229f721458ba5c6487286ec7b9d

## Acceptance Criteria

The chevron/arrow next to the table headers that are sortable should be clickable. 

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `refactor: <component_name> tests`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready for review" label when complete.

**Comment by taksuparth** [comment]
@nataliepina can pick this up
